### ISSUE TITLE
WLST didn't return a prompt after executing 'start-admin-server.py' script

### ISSUE THREAD

**Issue by abessifi** [cvezalis/weblogic-ansible#1]
After performing the command `"{{ weblogic_home }}/common/bin/wlst.sh {{ mw_installer_folder }}/start-admin-server.py"` the AdminServer seems to start correctly:
- 7001 port is opened
- It can access the adminserver web UI on http://foo.bar:7001
- in the AdminServer.out file I can see:

Apr 29, 2016 12:31:04 PM UTC Notice WebLogicServer BEA-000360 The server started in RUNNING mode. 
Apr 29, 2016 12:31:04 PM UTC Notice WebLogicServer BEA-000365 Server state changed to RUNNING.

**The command output :**

Initializing WebLogic Scripting Tool (WLST) ...
Welcome to WebLogic Server Administration Scripting Shell
Type help() for help on available commands
Connecting to Node Manager ...
Apr 29, 2016 12:30:30 PM UTC Info Security BEA-090905 Disabling the CryptoJ JCE Provider self-integrity check for better startup performance. To enable this check, specify -Dweblogic.security.allowCryptoJDefaultJCEVerification=true. 
Apr 29, 2016 12:30:31 PM UTC Info Security BEA-090906 Changing the default Random Number Generator in RSA CryptoJ from ECDRBG128 to HMACDRBG. To disable this change, specify -Dweblogic.security.allowCryptoJDefaultPRNG=true. 
Apr 29, 2016 12:30:31 PM UTC Info Security BEA-090909 Using the configured custom SSL Hostname Verifier implementation: weblogic.security.utils.SSLWLSHostnameVerifier$NullHostnameVerifier. 
Successfully Connected to Node Manager.
Starting server AdminServer ...

The problem is that after running the command the wlst didn't return the shell prompt and the output still blocked to the message "Starting server AdminServer ...".
I've ran the command `nmServerStatus('AdminServer');` and it returned:

Initializing WebLogic Scripting Tool (WLST) ...
Welcome to WebLogic Server Administration Scripting Shell
Type help() for help on available commands
Connecting to Node Manager ...
....
Successfully Connected to Node Manager.
**STARTING**
Successfully disconnected from Node Manager.

**Comment by cvezalis** [comment]
I cannot reproduce this. Maybe it is in older code.
